name: Continouse Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy-production:
    runs-on: ubuntu-20.04
    name: Deploy production
    environment:
      name: production
      url: https://gym.kishieel.cfolks.pl
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build frontend
        shell: bash
        run: |
          yarn install
          yarn build:prod
      - name: Move files
        shell: bash
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.rsa
          chmod 600 key.rsa
          rsync -az \
            --delete \
            --exclude=key.rsa \
            --exclude-from=.rsyncignore \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i key.rsa -o StrictHostKeyChecking=no" \
            . "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_TARGET }}"
      - name: Set release version
        id: release-version
        run: |
          echo "::set-output name=app-version::$(git describe --tags)"
      - name: Run deploy
        uses: appleboy/ssh-action@v0.1.1
        env:
          APP_VERSION: ${{ steps.release-version.outputs.app-version }}
        with:
          username: ${{ secrets.SSH_USER }}
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: APP_VERSION
          script: |
            php="$HOME/bin/php"
            composer="$php $HOME/bin/composer"

            cd ${{ secrets.SSH_TARGET }}
            echo "${{ secrets.ENV }}" > .env
            echo APP_VERSION=$APP_VERSION >> .env

            $composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --no-cache --no-progress
            $php artisan cache:clear
            $php artisan migrate --force
            $php artisan storage:link --force
            $php artisan optimize
            $php artisan queue:restart

            cd ..
            rm -rdf public_html
            ln -s ${{ secrets.SSH_TARGET }}/public public_html
